### ISSUE TITLE
NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by wenfangdu** [Lexikos/AutoHotkey_L-Docs#523]

**Comment by joedf** [comment]
This should be resolved now, and was being discussed here:
https://www.autohotkey.com/boards/viewtopic.php?p=423317#p423317
and
https://www.autohotkey.com/boards/viewtopic.php?f=3&t=95148

Please contact support [at] ahkscript.org instead in the future.

**Comment by wenfangdu** [comment]
@joedf You mean contact support at [AutoHotkey forum](https://www.autohotkey.com/boards/) instead? Since ahkscript.org redirects to autohotkey.com.

**Comment by joedf** [comment]
Yes, we have both domains. This is a server issue rather than a documentation. Either way, thanks for reporting this.

**Comment by csuhta** [comment]
This is not resolved for me in either Chrome or Safari as of this message. The certificate still descends from an invalid R3 intermediate. I've tried double-checking by clearing caches and the like. 

<img width="818" alt="GZORGT1N0v" src="https://user-images.githubusercontent.com/769083/136081920-015f6fd8-e8b7-426b-b5f1-7492f68e96a2.png">

**Comment by joedf** [comment]
Yes, this is still an issue. We do infact have an updated R3 certificate with validity:
```
Not Before: Fri, 04 Sep 2020 00:00:00 GMT
Not After: Mon, 15 Sep 2025 16:00:00 GMT
```

Things may still be bit out of sync. You might need to update your browsers, or maybe try firefox? Things are still slow and spotty.
